name: Jest Testing worflow - CI/CD

on:
  push:
    branches: 
    - 'develop'
    - '!main'
    - '!master'
    - '!feature*'
    - '!feature/*'
    - '!fix*'
    - '!fix/*'
    - '!hotfix*'
    - '!hotfix/*'
    - '!feat*'
    - '!feat/*'
  pull_request:
    branches:
    - 'develop'
    - '!main'
    - '!master'
    - '!feature*'
    - '!feature/*'
    - '!fix*'
    - '!fix/*'
    - '!hotfix*'
    - '!hotfix/*'
    - '!feat*'
    - '!feat/*'

jobs:
    Test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v2

            - name: Take package.json version
              id: package_version
              run: echo ::set-output name=package_version::$(node -p "require('./package.json').version")
    
            - name: Install dependencies
              run: npm config set legacy-peer-deps=true && npm install --legacy-peer-deps

            - name: Run tests
              run: npm test

            